import esbuild from "esbuild";
import { existsSync, mkdirSync } from "fs";
import { builtinModules } from 'node:module';
import path from "path";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Detect entry point: prefer src/main.ts, fallback to main.ts
const hasSrcMain = existsSync("src/main.ts");
const hasRootMain = existsSync("main.ts");

if (hasSrcMain && hasRootMain) {
  console.warn("WARNING: Both src/main.ts and main.ts exist. Using src/main.ts as entry point.");
  console.warn("Consider removing one to avoid confusion.");
}
if (!hasSrcMain && !hasRootMain) {
  console.error("ERROR: Neither src/main.ts nor main.ts found!");
  process.exit(1);
}

// Set entry point based on what exists
const entryPoint = hasSrcMain ? "src/main.ts" : "main.ts";

// Check if this is a one-time build or watch mode
const args = process.argv.slice(2);
const isOneTimeBuild = args.includes("build") || args.includes("production");

// 创建输出目录
const outDir = isOneTimeBuild ? "dist" : ".";
if (isOneTimeBuild && !existsSync(outDir)) {
  mkdirSync(outDir, { recursive: true });
  console.log(`📁 Created ${outDir} directory`);
}

const outfile = isOneTimeBuild 
  ? path.join(outDir, "main.js")
  : "main.js";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: isOneTimeBuild ? false : "inline", // build 时不生成 sourcemap
	treeShaking: true,
	outfile: outfile,
	minify: isOneTimeBuild, // build 时压缩
});

if (isOneTimeBuild) {
	// Production build: build once and exit
	await context.rebuild();
	console.log("\n✓ Build complete!");
	console.log("📦 Release files in dist folder:");
	console.log("   - dist/main.js (minified)");
	
	// 复制 manifest.json 和 styles.css 到 dist 目录（如果存在）
	const filesToCopy = ["manifest.json", "styles.css"];
	for (const file of filesToCopy) {
		if (existsSync(file)) {
			const destPath = path.join(outDir, file);
			// 使用 fs.copyFileSync 复制文件
			const fs = await import('fs');
			fs.copyFileSync(file, destPath);
			console.log(`   - dist/${file}`);
		}
	}
	
	console.log("\n💡 Upload these files to GitHub releases\n");
	await context.dispose();
	process.exit(0);
} else {
	// Development mode: watch for changes
	console.log("\n✓ Development build running in watch mode");
	console.log("📝 Building to main.js in root");
	console.log("💡 For production builds, run: pnpm build\n");
	await context.watch();
}